openapi: 3.0.3
info:
  description: |
    Email Addresses that aliases will forward to.
  version: 1.0.0
  title: postfix api - destination
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
tags:
  - name: destination
    description: Email Addresses that aliases will forward to.
paths:
  /destination:
    get:
      tags:
        - destination
      summary: Searches for Destinations based on provided parameters.  None of the parameters are required.  Calling this endpoint with no parameters will return all records.
      parameters:
        - in: query
          name: q
          description: Query to run against all destination email addresses.  Value provided is used to perform a `LIKE` query on the `destination` column.
          required: false
          schema:
            type: string
        - in: query
          name: active
          description: Filter on whether the destination is active or not
          required: false
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        '405':
          description: Invalid input
          $ref: '#/components/responses/InvalidInput'
    post:
      tags:
        - destination
      summary: Creates a new destination email address.  Please note that there is a `UNIQUE` restriction on `destination`, meaning you cannot have destinations that go to the exact same place.  This includes inactive/active destinations.  Therefore, if you wish to activate a destination, you must use the `PATCH` method.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
        description: Destination to be added.  Only the `destination` property is required.  All other fields are silently ignored.
        required: true
      responses:
        '201':
          description: successful operation will return an array with exactly one destination.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        '405':
          description: Invalid input
          $ref: '#/components/responses/InvalidInput'

  /destination/{destinationId}:
    get:
      tags:
        - destination
      summary: Gets Destination information for the specified destination ID.
      parameters:
        - in: path
          name: destinationID
          description: Destination ID of the email address destination you want to find
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        '405':
          description: Invalid input
          $ref: '#/components/responses/InvalidInput'
    patch:
      tags:
        - destination
      summary: Modifies a destination object
      parameters:
        - in: path
          name: destinationID
          description: Destination ID of the email address destination you want to update.
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
        description: Updated Destination object.  Only the `destination` and `active` properties are permitted.  Other properties are silently ignored.  **Note on updating the destination address:** It is RECOMMENDED, but not required, that you only update the destination address for small spelling mistakes or other minor corrections.  The documentation as to why to be completed at another date.
        required: true
      responses:
        '200':
          description: successful operation.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
        '405':
          description: Invalid input
          $ref: '#/components/responses/InvalidInput'
components:
  schemas:
    Alias:
      type: object
      properties:
        alias:
          type: string
          description: The part of the email address before the @.
        domain:
          type: string
          description: The part of the email address after the @.
        fullEmailAddress:
          type: string
          format: email
          description: Fully-qualified email address.
        destination:
          type: string
          format: email
          description: Where the email will go after.
        active:
          type: boolean
          description: Describes whether the alias is active or not.  In order for an alias to be active, all connected assets (i.e. the domain, the alias, and the destination) must be active.  When any connected assets are set to `false`, emails will bounce.
        ignore:
          type: boolean
          description: Describes whether the alias will ignore all mail.  Email sent to aliases set to ignore will NOT receive bounce but instead will be silently sent to `/dev/null`.  `active` must be `true` in order for emails to be silently ignored.
        uuid:
          type: string
          format: uuid
          description: UUID identifying the alias.  Deprecated.
        count:
          type: integer
          format: int32
          description: The number of times this alias has been sent an email.  Please note that this is in no way at all accurate and should only be used for statistical purposes.
        created:
          type: string
          description: The datetime of when the alias was created.
          format: date-time
        modified:
          type: string
          description: The datetime of when the alias was last used or modified.
          format: date-time
    Destination:
      type: object
      properties:
        destination:
          type: string
          format: email
          description: Fully-qualified email address
        active:
          type: boolean
    Domain:
      type: object
      properties:
        domain:
          type: string
          description: Fully-qualified domain name
        description:
          type: string
        active:
          type: boolean
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  responses:
    InvalidInput:
      description: Invalid input.  ErrorResponse message will have error information.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'