name: DEV QA -- Deploy S3 Lambda
on:
  push:
    branches:
      - 'dev-*'
      - 'qa-*'
    paths:
      - '**.js'
      - '.ci/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/aws-deploy.yaml'
      - '.github/workflows/deploy-s3-lambda.yaml'
      - '!src/bable.config.js'
      - '!src/index.js'
      - '!src/ses.js'

defaults:
  run:
    shell: bash
    working-directory: 'src/'

jobs:
  aws-deploy-ses-dev:
    if: startsWith(github.ref_name, 'dev-s3')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      function-name: tacomail-s3-handler-dev-${{ github.ref_name }}
      lambda-handler: s3handler.handler

  aws-deploy-ses-qa-prod:
    if: startsWith(github.ref_name, 'qa-s3')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      function-name: tacomail-s3-handler-qa-${{ github.ref_name }}
      lambda-handler: s3handler.handler
