name: Deploy API Lambdas
on:
  push:
    branches:
      - 'dev-*'
      - 'qa-*'
    paths:
      - '**.js'
      - '!src/bable.config.js'
      - '!index.js'

defaults:
  run:
    shell: bash
    working-directory: 'src/'

jobs:
  aws-deploy-ses-dev:
    if: startsWith(github.ref_name, 'dev-ses')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: development-ses
      lambda-handler: ses.export

  aws-deploy-qa-prod:
    if: startsWith(github.ref_name, 'qa-')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: production
