name: PROD - Deploy Lambdas
on:
  push:
    tags:
      - 'v*'

defaults:
  run:
    shell: bash
    working-directory: 'src/'


jobs:
  aws-deploy-ses-production:
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: production-ses
      lambda-handler: ses.export

  aws-deploy-api-prod:
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: production
      lambda-handler: index.handler

  aws-deploy-s3-handler-prod:
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      environment-name: production
      lambda-handler: s3handler.handler
