# Deploys the API Lambda
name: DEV QA -- Deploy API Lambda
on:
  push:
    branches:
      - 'dev-*'
      - 'qa-*'
    paths:
      - '**.js'
      - '.ci/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/aws-deploy.yaml'
      - '.github/workflows/deploy-api-lambda.yaml'
      - '!src/bable.config.js'
      - '!src/s3handlers.js'
      - '!src/ses.js'


defaults:
  run:
    shell: bash
    working-directory: 'src/'


jobs:
  aws-deploy-api-dev:
    if: startsWith(github.ref_name, 'dev-')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      function-name: tacomail-api-dev-${{ github.ref_name }}
      lambda-handler: index.handler

  aws-deploy-api-qa:
    if: startsWith(github.ref_name, 'qa-')
    uses: ./.github/workflows/aws-deploy.yaml
    secrets: inherit
    with: 
      function-name: tacomail-api-qa-${{ github.ref_name }}
      lambda-handler: index.handler
    